"""Legacy compatibility facade for the script-quality contract."""

from __future__ import annotations

from pathlib import Path
import re

from cyberppt.script_quality.audit import (
    ONSCREEN_SEMANTIC_COVERAGE_TARGET, VISIBLE_JUDGMENT_MIN_SIMILARITY,
    VISIBLE_JUDGMENT_TERMINAL_PUNCTUATION, SCOPE_TERMS, IMPLEMENTATION_TERMS,
    COMPOSITION_PRIMITIVES, SPATIAL_SIGNALS, STRATEGY_ORDER, _TERM_HEDGE_LEAD_RE,
    _TERM_HEDGE_TRAIL_CONDITION_RE, _TERM_HEDGE_TRAIL_NEGATION_RE, _unhedged_terms,
    _unhedged_scope_terms, _claim_text, build_communication_review, script_retry_directive,
    audit_script_quality,
)

from cyberppt.script_quality.models import (
    LOCKED_JUDGMENT_ROLES, ONSCREEN_JUDGMENT_MODES, SEMANTIC_ONLY_JUDGMENT_ROLES,
    PageRelationshipSummary, ScriptDocument, ScriptPage, ScriptQualityIssue, _issue,
    resolve_judgment_mode,
)

from cyberppt.script_quality.parsing import (
    FIELD_RE, HEADING_FIELD_ALIASES, HEADING_FIELD_RE, INLINE_MODULE_RE, MODULE_RE,
    NON_ONSCREEN_VISUAL_HEADING_RE, PAGE_CONTRACT_FIELDS, PAGE_CONTRACT_RECEIPT_RE,
    PAGE_HEADING_RE, SOURCE_RANGE_RE, SOURCE_RE, SPEAKER_SECTION_RE, _line_indent,
    _source_refs, audience_facing_group_label, extract_page_contract_receipt,
    extract_speaker_notes, load_page_contract_sidecar, parse_script_markdown,
    parse_script_path, strip_authoring_group_marker,
)

from cyberppt.script_quality.text_rules import (
    DEFENSIVE_BOUNDARY_COACHING_RE, FORMULAIC_TRANSITION_TERMS, NEGATION_TERMS,
    PROSE_MIN_CHARS, SPEAKER_HOST_META_RE, SPEAKER_NOTES_MIN_CHARS,
    SPEAKER_PLACEHOLDER_RE, SPEAKER_SLIDE_META_RE,
    _ANALYTICAL_VOICE_PATTERNS, _BOUNDARY_ASIDE_PATTERNS, _CONDITIONAL_RISK_PHRASES,
    _DIRECT_BOUNDARY_ARGUMENT_ROLES, _DIRECT_BOUNDARY_TOPIC_TERMS, _NEGATIVE_FOREGROUND_TERMS,
    _PROHIBITED_COLLOQUIAL_PATTERNS, _PROHIBITED_CONTRAST_PATTERNS, _analytical_voice_hits,
    _boundary_aside_hits, _formulaic_transition_issues, _is_direct_boundary_clarification,
    _leading_negative_foreground_terms, _narration_boundary_issues,
    _negative_foreground_issues, _negative_foreground_terms,
    _opening_negative_foreground_terms, _prohibited_colloquial_hits, _prohibited_contrast_hits,
    _prohibited_contrast_issues, _prose_issues, _selected_problem_slots,
    _speaker_placeholder_hits,
)

from cyberppt.script_quality.source_coverage import (
    _dict_items, _full_prose_paragraph_boundary_issues, _full_prose_source_coverage_issues,
    _model_slot_coverage_issues, _onscreen_enumeration_loss_issues, _onscreen_module_provenance_issues,
    _outline_pages, _page_content_unit_coverage_issues, _polarity_dropped_terms,
    _source_consumption_issues, _source_statement_overlap, _truth_records, _visible_module_groups,
    normalized_tokens, text_similarity,
)

from cyberppt.script_quality.onscreen import (
    ANTI_PATTERN_TERMS, BUSINESS_LANE_LABEL_RE, CONSTRAINT_ARGUMENT_ROLES,
    CONSTRAINT_THEME_TERMS, COUNT_WORDS, GENERIC_ONSCREEN_DETAIL_LABELS,
    GENERIC_ONSCREEN_GROUP_LABELS, GENERIC_ONSCREEN_RELATION_RE, LAYER_LIKE_INTENT_TYPES,
    LAYER_SIGNALS, LOOP_SIGNALS, MATRIX_SIGNALS, MECHANISM_LANE_LABEL_RE, MODULE_CEILING,
    NUMBERED_EVIDENCE_BULLET_RE, NUMBERED_ORDER_SIGNAL_RE, ONSCREEN_BACKEND_META_PHRASES,
    ONSCREEN_CONSTRAINT_DETAIL_TERMS, ONSCREEN_CONSTRAINT_MODULE_TERMS,
    ONSCREEN_DETAIL_PHRASE_ERROR_CHARS, ONSCREEN_DETAIL_PHRASE_WARNING_CHARS,
    ONSCREEN_EFFECTIVE_CHARS_MAX, ONSCREEN_EFFECTIVE_CHARS_MIN, ONSCREEN_FLOW_ACTION_TERMS,
    ONSCREEN_FLOW_HEADING_MAX_CHARS, ONSCREEN_LAYOUT_META_PATTERNS,
    ONSCREEN_PROSE_DENSITY_RATIO, ONSCREEN_RELATION_META_LABELS,
    ONSCREEN_SEMANTIC_COVERAGE_ERROR_FLOOR, ONSCREEN_SEMANTIC_COVERAGE_MIN,
    ONSCREEN_SOURCE_ERASURE_PHRASES,
    ONSCREEN_SOURCE_SPECIFICITY_ERROR_FLOOR, ONSCREEN_STORY_EXPLANATION_SIGNALS,
    ONSCREEN_STORY_IMPLICATION_SIGNALS, ONSCREEN_STORY_RELATION_SIGNALS, ORDER_SIGNALS,
    PATH_LIKE_INTENT_TYPES, SELECTION_NOTE_REQUIRED_MARKERS, SEMANTIC_STRUCTURE_SIGNALS,
    STYLE_ONLY_TERMS, VISUAL_STRUCTURE_LAYOUT_RECIPE_RES, VISUAL_STRUCTURE_MULTIPLE_PRIMARY_RE,
    _ACTOR_DUTY_LABEL_RE, _ACTOR_LABEL_RE, _ACTOR_PARENT_RE, _COMPOUND_HEADING_HEADS,
    _COMPOUND_HEADING_INCOMPATIBLE_HEADS, _COMPOUND_PARENT_DOMAINS, _MODULE_CEILING_FALLBACK,
    _NON_ACTOR_PARENT_RE, _OBJECT_TAXONOMY_PARENT_RE, _ONSCREEN_MARKDOWN_PATTERNS,
    _ONSCREEN_RELATION_META_RE, _RULES_YAML_PATH, _SEMANTIC_LINE_PATTERNS,
    _SUBORDINATE_DETAIL_RE, _TAXONOMY_CROSSCUT_LABEL_RE, _compound_module_heading_hits,
    _constraint_is_declared_subject, _declared_count, _generic_onscreen_relation_hits,
    _has_any, _load_module_ceiling, _mechanical_evidence_bullets,
    _mechanical_onscreen_label_pattern_hits, _module_heading_colon_hits, _nontable_compact_len,
    _onscreen_backend_meta_hits, _onscreen_constraint_module_hits,
    _onscreen_detail_phrase_overages, _onscreen_false_parallel_semantics,
    _onscreen_flat_long_labelled_detail_hits, _onscreen_flow_language_issues,
    _onscreen_heading_candidates, _onscreen_layout_meta_hits, _onscreen_markdown_hits,
    _onscreen_module_dimension_consistency_issues,
    _onscreen_parallel_structure_issues, _onscreen_parent_child_role_mismatches,
    _onscreen_redundant_restatement_issues,
    _onscreen_relation_meta_hits, _onscreen_subordinate_fragments, _page_relation_corpus,
    _page_text, _semantic_line_role, _subtitle_policy_issues, _unlabeled_onscreen_bullets,
    _visual_module_label, _visual_structure_chain_nodes, _visual_structure_layout_recipe_hits,
    assert_imagegen_onscreen_readiness, meaningful_char_count, onscreen_effective_char_target,
    onscreen_semantic_coverage, onscreen_story_roles, parse_selection_notes,
    selection_notes_are_structured, _necessity_page_closure_issues,
)

from cyberppt.script_quality.final_form import (
    FINAL_BATCH_HEADING_RE, FINAL_BATCH_META_RE, FINAL_DRAFT_HEADING_RE, FINAL_DRAFT_STATUS_RE,
    FINAL_PENDING_AUDIT_RE, audit_final_manuscript_form, is_final_script_path,
)

from cyberppt.script_quality.presentation import (
    COMPLETED_TERMS, CONDITIONAL_STATUSES, VISIBLE_CERTAINTY_TERMS, _preflight_semantic_issues,
    _presentation_issues, _visual_structure_judgment_issues,
)

from cyberppt.script_quality.relationships import (
    _RELATION_ACTION_SIGNALS, _RELATION_VISIBILITY_SIGNALS, _contract_relations,
    _has_visible_declared_relation, _page_relationship_continuity_issues,
    _page_relationship_summary, _preempted_scope_terms, _relation_corpus,
    _relation_parallel_labels, _relation_values, _relation_visibility_signal,
    _relationship_prerequisite_issue, _relationship_strings, _same_page_responsibility,
)


__all__ = (
    "ANTI_PATTERN_TERMS", "BUSINESS_LANE_LABEL_RE", "COMPLETED_TERMS",
    "COMPOSITION_PRIMITIVES", "CONDITIONAL_STATUSES", "CONSTRAINT_ARGUMENT_ROLES",
    "CONSTRAINT_THEME_TERMS", "COUNT_WORDS", "DEFENSIVE_BOUNDARY_COACHING_RE", "FIELD_RE",
    "FINAL_BATCH_HEADING_RE", "FINAL_BATCH_META_RE", "FINAL_DRAFT_HEADING_RE",
    "FINAL_DRAFT_STATUS_RE", "FINAL_PENDING_AUDIT_RE", "FORMULAIC_TRANSITION_TERMS",
    "GENERIC_ONSCREEN_DETAIL_LABELS", "GENERIC_ONSCREEN_GROUP_LABELS",
    "GENERIC_ONSCREEN_RELATION_RE", "HEADING_FIELD_ALIASES", "HEADING_FIELD_RE",
    "IMPLEMENTATION_TERMS", "INLINE_MODULE_RE", "LAYER_LIKE_INTENT_TYPES", "LAYER_SIGNALS",
    "LOCKED_JUDGMENT_ROLES", "LOOP_SIGNALS", "MATRIX_SIGNALS", "MECHANISM_LANE_LABEL_RE",
    "MODULE_CEILING", "MODULE_RE", "NEGATION_TERMS", "NON_ONSCREEN_VISUAL_HEADING_RE",
    "NUMBERED_EVIDENCE_BULLET_RE",
    "NUMBERED_ORDER_SIGNAL_RE", "ONSCREEN_BACKEND_META_PHRASES",
    "ONSCREEN_CONSTRAINT_DETAIL_TERMS", "ONSCREEN_CONSTRAINT_MODULE_TERMS",
    "ONSCREEN_DETAIL_PHRASE_ERROR_CHARS", "ONSCREEN_DETAIL_PHRASE_WARNING_CHARS",
    "ONSCREEN_EFFECTIVE_CHARS_MAX", "ONSCREEN_EFFECTIVE_CHARS_MIN",
    "ONSCREEN_FLOW_ACTION_TERMS", "ONSCREEN_FLOW_HEADING_MAX_CHARS", "ONSCREEN_JUDGMENT_MODES",
    "ONSCREEN_LAYOUT_META_PATTERNS", "ONSCREEN_PROSE_DENSITY_RATIO",
    "ONSCREEN_RELATION_META_LABELS", "ONSCREEN_SEMANTIC_COVERAGE_ERROR_FLOOR",
    "ONSCREEN_SEMANTIC_COVERAGE_MIN", "ONSCREEN_SEMANTIC_COVERAGE_TARGET",
    "ONSCREEN_SOURCE_ERASURE_PHRASES",
    "ONSCREEN_SOURCE_SPECIFICITY_ERROR_FLOOR", "ONSCREEN_STORY_EXPLANATION_SIGNALS",
    "ONSCREEN_STORY_IMPLICATION_SIGNALS", "ONSCREEN_STORY_RELATION_SIGNALS", "ORDER_SIGNALS",
    "PAGE_CONTRACT_FIELDS", "PAGE_CONTRACT_RECEIPT_RE", "PAGE_HEADING_RE",
    "PATH_LIKE_INTENT_TYPES", "PROSE_MIN_CHARS", "PageRelationshipSummary", "Path",
    "SCOPE_TERMS", "SELECTION_NOTE_REQUIRED_MARKERS", "SEMANTIC_ONLY_JUDGMENT_ROLES",
    "SEMANTIC_STRUCTURE_SIGNALS", "SOURCE_RANGE_RE", "SOURCE_RE", "SPATIAL_SIGNALS",
    "SPEAKER_HOST_META_RE",
    "SPEAKER_NOTES_MIN_CHARS", "SPEAKER_PLACEHOLDER_RE", "SPEAKER_SLIDE_META_RE",
    "SPEAKER_SECTION_RE", "STRATEGY_ORDER", "STYLE_ONLY_TERMS", "ScriptDocument",
    "ScriptPage", "ScriptQualityIssue",
    "VISIBLE_CERTAINTY_TERMS", "VISIBLE_JUDGMENT_MIN_SIMILARITY",
    "VISIBLE_JUDGMENT_TERMINAL_PUNCTUATION", "VISUAL_STRUCTURE_LAYOUT_RECIPE_RES",
    "VISUAL_STRUCTURE_MULTIPLE_PRIMARY_RE", "_ACTOR_DUTY_LABEL_RE", "_ACTOR_LABEL_RE",
    "_ACTOR_PARENT_RE", "_ANALYTICAL_VOICE_PATTERNS", "_BOUNDARY_ASIDE_PATTERNS",
    "_COMPOUND_HEADING_HEADS", "_COMPOUND_HEADING_INCOMPATIBLE_HEADS",
    "_COMPOUND_PARENT_DOMAINS", "_CONDITIONAL_RISK_PHRASES", "_DIRECT_BOUNDARY_ARGUMENT_ROLES",
    "_DIRECT_BOUNDARY_TOPIC_TERMS", "_MODULE_CEILING_FALLBACK", "_NEGATIVE_FOREGROUND_TERMS",
    "_NON_ACTOR_PARENT_RE", "_OBJECT_TAXONOMY_PARENT_RE", "_ONSCREEN_MARKDOWN_PATTERNS",
    "_ONSCREEN_RELATION_META_RE", "_PROHIBITED_COLLOQUIAL_PATTERNS",
    "_PROHIBITED_CONTRAST_PATTERNS", "_RELATION_ACTION_SIGNALS",
    "_RELATION_VISIBILITY_SIGNALS", "_RULES_YAML_PATH", "_SEMANTIC_LINE_PATTERNS",
    "_SUBORDINATE_DETAIL_RE", "_TAXONOMY_CROSSCUT_LABEL_RE", "_TERM_HEDGE_LEAD_RE",
    "_TERM_HEDGE_TRAIL_CONDITION_RE", "_TERM_HEDGE_TRAIL_NEGATION_RE",
    "_analytical_voice_hits", "_boundary_aside_hits", "_claim_text",
    "_compound_module_heading_hits", "_constraint_is_declared_subject", "_contract_relations",
    "_declared_count", "_dict_items", "_formulaic_transition_issues",
    "_full_prose_paragraph_boundary_issues", "_full_prose_source_coverage_issues",
    "_generic_onscreen_relation_hits", "_has_any", "_has_visible_declared_relation",
    "_is_direct_boundary_clarification", "_issue", "_leading_negative_foreground_terms",
    "_line_indent", "_load_module_ceiling", "_mechanical_evidence_bullets",
    "_mechanical_onscreen_label_pattern_hits", "_model_slot_coverage_issues",
    "_module_heading_colon_hits", "_narration_boundary_issues",
    "_necessity_page_closure_issues", "_negative_foreground_issues",
    "_negative_foreground_terms", "_nontable_compact_len", "_onscreen_backend_meta_hits",
    "_onscreen_constraint_module_hits", "_onscreen_detail_phrase_overages",
    "_onscreen_enumeration_loss_issues",
    "_onscreen_false_parallel_semantics", "_onscreen_flat_long_labelled_detail_hits",
    "_onscreen_flow_language_issues", "_onscreen_heading_candidates",
    "_onscreen_layout_meta_hits", "_onscreen_markdown_hits",
    "_onscreen_module_dimension_consistency_issues",
    "_onscreen_module_provenance_issues", "_onscreen_parallel_structure_issues",
    "_onscreen_parent_child_role_mismatches", "_onscreen_redundant_restatement_issues",
    "_onscreen_relation_meta_hits",
    "_onscreen_subordinate_fragments", "_opening_negative_foreground_terms", "_outline_pages",
    "_page_content_unit_coverage_issues", "_page_relation_corpus",
    "_page_relationship_continuity_issues", "_page_relationship_summary", "_page_text",
    "_polarity_dropped_terms", "_preempted_scope_terms", "_preflight_semantic_issues",
    "_presentation_issues", "_prohibited_colloquial_hits", "_prohibited_contrast_hits",
    "_prohibited_contrast_issues", "_prose_issues", "_relation_corpus",
    "_relation_parallel_labels", "_relation_values", "_relation_visibility_signal",
    "_relationship_prerequisite_issue", "_relationship_strings", "_same_page_responsibility",
    "_selected_problem_slots", "_semantic_line_role", "_source_consumption_issues",
    "_source_refs", "_source_statement_overlap", "_speaker_placeholder_hits",
    "_subtitle_policy_issues", "_truth_records", "_unhedged_scope_terms", "_unhedged_terms",
    "_unlabeled_onscreen_bullets", "_visible_module_groups", "_visual_module_label",
    "_visual_structure_chain_nodes", "_visual_structure_judgment_issues",
    "_visual_structure_layout_recipe_hits", "annotations",
    "assert_imagegen_onscreen_readiness", "audience_facing_group_label",
    "audit_final_manuscript_form", "audit_script_quality", "build_communication_review",
    "extract_page_contract_receipt", "extract_speaker_notes", "is_final_script_path",
    "load_page_contract_sidecar", "meaningful_char_count", "normalized_tokens",
    "onscreen_effective_char_target", "onscreen_semantic_coverage", "onscreen_story_roles",
    "parse_script_markdown", "parse_script_path", "parse_selection_notes", "re",
    "resolve_judgment_mode", "script_retry_directive", "selection_notes_are_structured",
    "strip_authoring_group_marker", "text_similarity",
)
